### ISSUE TITLE
Infinite loop parsing incorrect INF

### ISSUE THREAD

**Issue by Phasip** [arutar/wininfparser#3]
Hello again, thanks for the last fix.

I stumbled upon another faulty INF that I managed to cut down to this:
```
#!/usr/bin/python3
import wininfparser
import tempfile

with tempfile.NamedTemporaryFile() as t:
    t.write(b"""[a]
b==c
""")
    t.flush()
    x = wininfparser.WinINF()
    x.ParseFile(t.name)
```

Please note that I'm not trying to find issues, I'm just parsing older INFs using your code.
I completely understand that handling all edge cases may not be your priority.

**Comment by arutar** [comment]
New version available.
